[package]
name = "metrics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
anyhow.workspace = true
prometheus.workspace = true
lazy_static.workspace = true

[dev-dependencies]
tokio-test = "0.4"
